Pearson-Higher-Ed/elements

docs/elements/buttons.md, scss/_buttons.scss, scss/_variables.scss, scss/mixins/_buttons.scss
@dstack I realize that there will be an eventual merge conflict with the type/labels stuff.
Basic features for buttons.
=> feat(buttons): add buttons

docs/_data/nav.yaml, docs/elements/responsive-utilities.md, scss/_mixins.scss, scss/_responsive-utilities.scss, scss/_variables.scss, scss/elements.scss, scss/mixins/_responsive-breakpoints.scss, scss/mixins/_visibility.scss
@dstack
Add breakpoints, media query mixin, and visibility helper classes,
including accessibility helpers.
=> feat(responsive utilities): add responsive utilities

.gitignore, .travis.yml, test/shell_scripts/run_tests.sh, test/shell_scripts/tests_build_status.sh
Run Selenium Tests as part of CI.
=> feat: Run tests in CI

scss/_mixins.scss, scss/_plain-tags.scss, scss/_type.scss, scss/_variables.scss, scss/mixins/_headings.scss, test/fixtures/type/headings.html, test/spec/type.js
New typography styles added for h1 to h6 tags and classes per DES-116 & GCAPI-1049.
=> Add new typography styles for headings

scss/_buttons.scss
Focus outline was not showing in firefox, added outline to two buttons when in focus.
=> focus outline on btn-primary and pe--link

docs/elements/typography.md, scss/_type.scss, scss/_variables.scss, test/fixtures/type/lists.html, test/spec/type.js
Done all list changes with one line class for ol, and ul,
added ol and ul, with having header on top of list(s)
=> Add new typography styles for lists

docs/elements/inputs.md, docs/elements/typography.md, scss/_inputs.scss, scss/_mixins.scss, scss/_plain-tags.scss, scss/_type.scss, scss/_variables.scss, scss/mixins/_body.scss, test/spec/type.js
...and ready inputs.md for next merge
=> feat(typography): manually add Gayan's PR #58 plus changes

docs/elements/buttons.md, docs/elements/inputs.md, docs/scss/_icons.scss, scss/_buttons.scss, scss/_inputs.scss, scss/_variables.scss, scss/mixins/_responsive-breakpoints.scss
1. Added Medium button styles required for search
2. Added input-group styles required for search
=> Des 210 search

scss/mixins/_inputs.scss
bug fix for Box shadow in text input , related to mobile testing.
=> bug fix in text input mobile test.

docs/elements/inputs.md, scss/_mixins.scss, scss/_select-box.scss, scss/_variables.scss, scss/elements.scss, scss/mixins/_select-box.scss
=> Add Select box style and documantation

README.md, how-to-add-an-icon.md
=> fix(docs): move icons docs, point to them in README

docs/elements/calendar.md, scss/mixins/_calendar.scss
Link to bug issue on Laxapana board http://jira.pearsoncmg.com/jira/browse/GCAPI-1266
=> fix: calendar disabled state

scss/_calendar.scss, scss/_variables.scss, scss/mixins/_calendar.scss
Otherwise on a coloured web page, the calendar is not white. @umahaea @wyseguyonline  or whoever may review.
=> fix: add background-color to calendar

docs/elements/inputs.md
@umahaea or @veerabvm these classes never did anything so I'm removing them... tests should check that this still works.
=> refactor(inputs): remove unused classes, adjust documentation for radios

scss/mixins/_headings.scss
@umahaea http://jira.pearsoncmg.com/jira/browse/DES-382
=> fix(headings): h5 and h6 unbolded

docs/_data/nav.yaml, docs/elements/meter.md, scss/_meter.scss, scss/_variables.scss, scss/elements.scss
=> Add in meter and all associated styles

README.md, docs/_data/nav.yaml, docs/elements/grid.md, scss/_grid.scss, scss/_mixins.scss, scss/_variables.scss, scss/elements.scss, scss/mixins/_grid.scss
=> feat: add responsive grid

.travis.yml
Hipchat notifications now generating to channel Pearson Design Accelerator -CI
=> chore: Added hipchat notifications to elements

README.md, docs/_data/nav.yaml, docs/elements/grid.md, docs/elements/templates.md, scss/_mixins.scss, scss/_templates.scss, scss/_variables.scss, scss/elements.scss, scss/mixins/_grid.scss, scss/mixins/_templates.scss, scss/mixins/_utilities.scss
update to pe-template__double > :first-child from pe-template__double  :first-child
add link to design page in docs....
=> feat: add responsive templates

scss/_responsive-utilities.scss
https://medium.com/@jessebeach/beware-smushed-off-screen-accessible-text-5952a4c2cbfe#.aiorbeif8
=> prevent linefeed smushing

docs/elements/color.md
=> docs: Updated docs on how to use Colors component.

README.md
@wyseguyonline @JasonLantz @umahaea @mhomolak docs changes only
=> docs: update readme for v1

scss/elements/buttons/_buttons.scss
this is to keep from clobbering "primary" in the buttons selector....
=> fix: make class selector more specific to buttons

README.md, docs/_helpers/demo.js, docs/elements/inputs.md, scss/elements/inputs/_inputs.scss, scss/elements/inputs/_mixins.scss, scss/elements/inputs/_variables.scss
adds style for the hide/show button to facilitate password input in compounds.
=> feat: add passwordInput

docs/elements/inputs.md, scss/elements/inputs/_mixins.scss
we didn't have an explicit style to apply the blue color to the label.... this adds a class and an example for both style of inputs.
=> chore: add label focus style and example

scss/elements/inputs/_mixins.scss, scss/elements/inputs/_variables.scss
Correct line height now being applied to input labels.
=> fix: line height per red lines

docs/elements/inputs.md, scss/elements/inputs/_inputs.scss, scss/elements/inputs/_mixins.scss
@Sauravvaidya 's mixin for adding an error message to inputs....
=> feat: add error message for inputs

scss/elements/inputs/_variables.scss
Correct font size rendering for Inputs
=> Placeholder fix

scss/elements/buttons/_buttons.scss
Tory was informed of another design tweak to the link buttons..
=> chore: another design request

docs/elements/typography.md, scss/elements/typography/_type.scss
This is for the issue https://github.com/Pearson-Higher-Ed/elements/issues/193
=> remove b tags and use CSS for styling

scss/elements/modal/_mixins.scss
remove default margin on h2 in header....
=> fix: remove default margin on h2 in header

README.md, scss/elements/typography/_type.scss, scss/elementsNoPlain.scss
@mhomolak @wyseguyonline @JasonLantz @umahaea @udhadpa
=> feat: added two optional classes; updated documentation

scss/elements/modal/_mixins.scss
@tsrahm needed a fix...
this just removes the clearfix hack from modalContent.
=> fix: remove clearfix from modalContent

docs/elements/templates.md, scss/elements/templates/_mixins.scss, scss/elements/templates/_variables.scss
this was already approved and includes the updates for 10col and 6/6 double...
=> feat: add 10col and 6/6 double

README.md, docs/elements/index.md, package.json
to ---->
with components spreadsheet as reference.
=> chore: update design doc versions

scss/elements/inputs/_variables.scss
@mhomolak @wyseguyonline @umahaea @udhadpa
=> make placeholder pass contrast minimums: medium-gray instead of concrete

.travis.yml, CHANGELOG.md, package.json, scss/elements/color/_variables.scss
- This was done in Elements-SDK but never ported over to here.  It needs to be done to align with coach-mark specs.
=> fix: Update color hex
